"""tags support. MVP v0.02

Revision ID: 26198badd98a
Revises: 82bc77a4bbe2
Create Date: 2015-01-11 23:33:50.708956

"""

# revision identifiers, used by Alembic.
revision = '26198badd98a'
down_revision = '82bc77a4bbe2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=32), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_introduced',
        sa.Column('product_postid', sa.String(32), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['product_postid'], ['products.postid'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('users_translated',
        sa.Column('product_postid', sa.String(32), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['product_postid'], ['products.postid'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('products_tags',
        sa.Column('tag_id', sa.Integer(), nullable=True),
        sa.Column('product_postid', sa.String(32), nullable=True),
        sa.ForeignKeyConstraint(['product_postid'], ['products.postid'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.add_column(u'groups', sa.Column('member', sa.Boolean(), nullable=True))
    op.add_column(u'groups', sa.Column('perm_comment', sa.Boolean(), nullable=True))
    op.add_column(u'groups', sa.Column('perm_report', sa.Boolean(), nullable=True))
    op.add_column(u'groups', sa.Column('perm_review', sa.Boolean(), nullable=True))
    op.add_column(u'groups', sa.Column('perm_setgroup', sa.Boolean(), nullable=True))
    op.add_column(u'groups', sa.Column('perm_topic', sa.Boolean(), nullable=True))
    op.add_column(u'groups', sa.Column('perm_translate', sa.Boolean(), nullable=True))
    op.drop_column(u'groups', 'editproduct')
    op.drop_column(u'groups', 'deleteproduct')
    op.add_column(u'products', sa.Column('cintro', sa.Text(), nullable=True))
    op.add_column(u'products', sa.Column('cintro_locked', sa.Boolean(), nullable=True))
    op.add_column(u'products', sa.Column('cintro_locked_user_id', sa.Integer(), nullable=True))
    op.add_column(u'products', sa.Column('ctagline_locked', sa.Boolean(), nullable=True))
    op.add_column(u'products', sa.Column('ctagline_locked_user_id', sa.Integer(), nullable=True))
    op.add_column(u'products', sa.Column('editing_cintro_user_id', sa.Integer(), nullable=True))
    op.add_column(u'products', sa.Column('editing_ctagline_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['editing_cintro_user_id'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['ctagline_locked_user_id'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['editing_ctagline_user_id'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['cintro_locked_user_id'], ['id'])
    op.add_column(u'users', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.add_column(u'users', sa.Column('wbuid', sa.String(length=16), nullable=True))
    op.drop_column(u'users', 'signature')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('signature', sa.TEXT(), nullable=True))
    op.drop_column(u'users', 'wbuid')
    op.drop_column(u'users', 'nickname')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column(u'products', 'editing_ctagline_user_id')
    op.drop_column(u'products', 'editing_cintro_user_id')
    op.drop_column(u'products', 'ctagline_locked_user_id')
    op.drop_column(u'products', 'ctagline_locked')
    op.drop_column(u'products', 'cintro_locked_user_id')
    op.drop_column(u'products', 'cintro_locked')
    op.drop_column(u'products', 'cintro')
    op.add_column(u'groups', sa.Column('deleteproduct', sa.BOOLEAN(), nullable=False))
    op.add_column(u'groups', sa.Column('editproduct', sa.BOOLEAN(), nullable=False))
    op.drop_column(u'groups', 'perm_translate')
    op.drop_column(u'groups', 'perm_topic')
    op.drop_column(u'groups', 'perm_setgroup')
    op.drop_column(u'groups', 'perm_review')
    op.drop_column(u'groups', 'perm_report')
    op.drop_column(u'groups', 'perm_comment')
    op.drop_column(u'groups', 'member')
    op.drop_table('products_tags')
    op.drop_table('users_translated')
    op.drop_table('users_introduced')
    op.drop_table('tags')
    ### end Alembic commands ###
